// Writes REPORT.md (status of all countries) and CREDITS.md (attribution).
// Both are rewritten on every full build, so the report and the shipped data
// never drift apart.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Anthem } from '../../src/index.ts';
import { ROOT } from './cache.ts';
import type { AnthemConfig, Sources } from './config.ts';
import type { Countries } from './countries.ts';
import { scoreHost, type LoadedSource, type SourceRef } from './sources.ts';

export type Status = 'ok' | 'skipped' | 'missing' | 'error';

export interface CountryResult {
  status: Status;
  reason?: string;
  cfg?: AnthemConfig;
  /** Set for countries that share the melody of another country. */
  sameAs?: string;
  out?: Anthem;
  src?: LoadedSource;
  errors?: string[];
  flags?: string[];
}

export const NO_SOURCE = 'no freely licensed machine-readable score found';

const esc = (s: unknown): string => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const link = (url: string | null | undefined, text: string): string => (url ? `[${esc(text)}](${url})` : esc(text));

export function sourceLabel(src: SourceRef | undefined): string {
  if (!src) return '';
  if (src.type === 'commons') return src.file.replace(/^File:/, 'Commons: ');
  return `${/wikisource/.test(scoreHost(src)) ? 'Wikisource' : 'Wikipedia'} (${src.lang}): ${src.page}`;
}

export interface ReportInput {
  results: Record<string, CountryResult>;
  countries: Countries;
  sources: Sources;
  /** Anthem titles for countries without an entry in sources.json (from the Wikidata snapshot). */
  titles: Record<string, string>;
}

export function writeReport({ results, countries, sources, titles }: ReportInput): void {
  const rows: string[] = [];
  const counts: Record<Status, number> = { ok: 0, skipped: 0, missing: 0, error: 0 };
  for (const [code, country] of Object.entries(countries)) {
    const r = results[code] ?? { status: 'missing', reason: NO_SOURCE };
    const cfg = r.cfg ?? sources[code];
    counts[r.status]++;
    let status: string = r.status;
    let source = '';
    let license = '';
    let notes = r.reason ?? '';
    if (r.sameAs) {
      status = `ok (= ${r.sameAs})`;
      notes = cfg?.note ?? `same melody as ${r.sameAs}`;
    } else if (r.out) {
      source = link(r.src?.url, sourceLabel(cfg?.src));
      license = r.out.license;
      notes = [...(r.errors ?? []), ...(r.flags ?? []), cfg?.note].filter(Boolean).join('; ');
    }
    const regions = country.regions.map((x) => x.region).join(', ');
    const conf = r.status === 'ok' ? (cfg?.confidence ?? '') : '';
    const title = cfg?.title ?? titles[code] ?? '';
    rows.push(`| ${code} | ${esc(country.name)} | ${esc(regions)} | ${esc(status)} | ${esc(title)} | ${source} | ${esc(license)} | ${esc(conf)} | ${esc(notes)} |`);
  }
  const md = `# Report

Generated by \`npm run build\` - do not edit by hand.

Countries: ${Object.keys(countries).length} - ok: ${counts.ok}, skipped: ${counts.skipped}, missing: ${counts.missing}, error: ${counts.error}

Status: **ok** = shipped (\`anthems/\`); **skipped** = deliberately left out (usually because the composition is still under copyright);
**missing** = no usable freely licensed source found yet (contributions welcome, see README); **error** = source present, but the plausibility checks failed.

Confidence: **high** = confirmed by the interval test (\`test/known.test.ts\`) or several matching sources;
**medium** = clean source (score/vocal part), checks passed, but not compared against a second source;
**low** = source or track choice uncertain, see the notes.

| Code | Country | Region(s) | Status | Anthem | Source | License | Confidence | Notes |
|---|---|---|---|---|---|---|---|---|
${rows.join('\n')}
`;
  writeFileSync(join(ROOT, 'REPORT.md'), md);

  const credits: string[] = [];
  for (const code of Object.keys(results).sort()) {
    const r = results[code]!;
    if (!r.out || !r.src || !r.cfg) continue;
    const s = r.src;
    credits.push(
      `- **${code}** - ${esc(r.cfg.title)} (${esc(r.out.composer)}): ${link(s.url, sourceLabel(r.cfg.src))}` +
        `; author: ${esc(s.author)}; license: ${s.licenseUrl ? link(s.licenseUrl, s.license) : esc(s.license)}` +
        (s.fileUrl && s.fileUrl !== s.url ? `; MIDI: ${s.fileUrl}` : ''),
    );
  }
  writeFileSync(
    join(ROOT, 'CREDITS.md'),
    `# Credits

Generated by \`npm run build\`.

The melodies themselves are in the public domain (composer dead for more than
70 years, or traditional; see REPORT.md). The *scores* we extract them from
come from Wikimedia Commons, from LilyPond scores in Wikipedia articles and
from Wikisource transcriptions, and some of them are licensed CC BY-SA. The
derived note data in \`anthems/\` therefore keeps the license of its source,
file by file: if you use it, credit the sources listed below (and share
alike where the source is CC BY-SA). Every JSON file carries its own
\`source\`, \`author\` and \`license\`.

The MIT license of this repository covers the scripts only, not the data.

${credits.join('\n')}
`,
  );
}
